name: manual Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    uses: mngoe/openimis-fe_js/.github/workflows/module-ci-build.yml@feature-37406  # Adjust the path and branch as needed
    secrets:
      inherit
    with:
      branchName: ${{ github.head_ref || github.ref_name }}